# Handling Missing Values.

**.... Prev Continous

# Age Column

In [80]:
imputer = datawig.SimpleImputer(
    input_columns=['Pclass','SibSp'],
    output_column='Age')
imputer.fit(train_df = titanic_df)
imputed = imputer.predict(titanic_df)

In [81]:
imputed.drop(['Age'],axis=1,inplace=True)

In [82]:
imputed.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex  SibSp  Parch  \
0                            Braund, Mr. Owen Harris    male      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female      1      0   
2                             Heikkinen, Miss. Laina  female      0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female      1      0   
4                           Allen, Mr. William Henry    male      0      0   

             Ticket     Fare Embarked  Age_imputed  
0         A/5 21171   7.2500        S    25.078298  
1          PC 17599  71.2833        C    37.283546  
2  STON/O2. 3101282   7.9250        S    27.822079  
3            113803  53.1000        S    37.283546  
4            373450   8.0500        S    27.822079

In [83]:
df = imputed

## Make sure no null rows.

In [86]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
Age_imputed    0
dtype: int64

### Apply ZScore to Dataframe

In [87]:
numerics = ['int16', 'int32', 'int64', 'float16', 'float32', 'float64']
newdf = df.select_dtypes(include=numerics)

In [90]:
from scipy import stats

In [91]:
z = np.abs(stats.zscore(newdf))
print(z)

[[1.73010796 0.78927234 0.82737724 ... 0.47367361 0.50244517 0.80671378]
 [1.72622007 1.2669898  1.56610693 ... 0.47367361 0.78684529 1.26528415]
 [1.72233219 1.2669898  0.82737724 ... 0.47367361 0.48885426 0.3409216 ]
 ...
 [1.72233219 0.78927234 0.82737724 ... 2.00893337 0.17626324 0.80671378]
 [1.72622007 1.2669898  1.56610693 ... 0.47367361 0.04438104 1.48472432]
 [1.73010796 0.78927234 0.82737724 ... 0.47367361 0.49237783 0.3409216 ]]


### Data where outliers is located more than 3 std.

In [95]:
df_o = newdf[(z < 3).all(axis=1)]

In [96]:
df_o.shape

(827, 7)

### Final Data without outliers

In [97]:
df_o.head()

PassengerId  Survived  Pclass  SibSp  Parch     Fare  Age_imputed
0            1         0       3      1      0   7.2500    25.078298
1            2         1       1      1      0  71.2833    37.283546
2            3         1       3      0      0   7.9250    27.822079
3            4         1       1      1      0  53.1000    37.283546
4            5         0       3      0      0   8.0500    27.822079

** This only apply zscore to numerics column, other categorical column can be conactenated with numeric column after apply OHE or LabelEncoder.